### ISSUE TITLE
Scrolling with stick on browser sucks

### ISSUE THREAD

**Issue by emulamer** [emulamer/BeatOn#12]
Reports that scrolling using the stick on the iframe browser window is awful.

**Comment by xAgent42x** [comment]
Scrolling with SideQuest Wrapper2 app launcher is very smooth.  Just FYI.

**Comment by emulamer** [comment]
I believe this is happening because when it is launched from oculus TV, it gets launched in d-pad mode with "touch mode" disabled, so the stick navigates between elements on the pages rather than scrolling the page.  I'll have to see if there's some way to force the app into "touch mode"

**Comment by emulamer** [comment]
This one is going to be a pain in the neck.  It looks like it's launching inside a virtual display with touch disabled.  I'll probably have to look at killing and immediately relaunching the app if it finds touch disabled... or something.  Maybe find a way to launch it outside of oculus tv.
