### ISSUE TITLE
Downloading and sideloading songs.

### ISSUE THREAD

**Issue by xAgent42x** [emulamer/BeatOn#13]
Sideloaded about 80 songs with old file naming extension from Bsaber.com.  Once those were complete I downloaded more random songs through BeatOn.  Hit about 190 songs and at some point something broke and Beat Saber would not get past intro splash and would crash to dashboard.  I downloaded songs at a high rate of speed and then clicked sync with beat saber button once cloud was at zero.  Not sure what caused the issue but Reset Assets then Reload Songs Folder fixed the issue.

**Comment by emulamer** [comment]
Writing assets should be more reliable now, I tested up to about 250 and it didn't crash out.  still some instability in the new asset code though.
