### ISSUE TITLE
Content type incorrectly detected for zips with mods on MacOS

### ISSUE THREAD

**Issue by a1c0r** [emulamer/BeatOn#24]
When uploading mods as zip files, the app expects MIME type as "application/x-zip-compressed", which is correct on Windows. However on MacOS both Chrome and Safari upload file as application/zip which fails the validation.
Consider accepting both types.

**Comment by emulamer** [comment]
Think this might be addressed in 0.0.9.6 since I'm not checking the mime type as aggressively, but I'll check it on a mac and make sure.

**Comment by KarlDeux** [comment]
@a1c0r do you still have this issue?

**Comment by a1c0r** [comment]
I tried BeatOn with SideQuest and could upload the mods from MacOS, so it must be fixed.
