### ISSUE TITLE
How to use pc to customize sabers？

### ISSUE THREAD

**Issue by cgapk123** [emulamer/BeatOn#27]
Beaton does not work, how to customize the saber in pc patched beatsaber.apk

**Comment by dezi88** [comment]
Worked fine with beaton for me.
You download the zip file for the new saber ( should be in the release) and when you go to the website for beaton in a internetbrowser on your pc, you can drop it in the upload tap. You can see the link in the tools tap in beaton on the quest under tools.

**Comment by cgapk123** [comment]
Failed, Critical Error
Something has gone wrong and Beat On can't function. Try Reset Assets in the tools menu.

I don't know why, I know that the katanaV1 file contains the json data structure, can the beaton provide questsaberpatch similar? Example: json2App.exe < beatonmod.json

**Comment by sc2ad** [comment]
QuestSaberPatch (both my fork and trishume's original) does not support asset injection for custom sabers. The problem you are having is likely due to a version problem- BeatOn may not support older versions of Beat Saber reliably. I'll look into this and close this when we can replicate the issue and find a fix.

**Comment by cgapk123** [comment]
> QuestSaberPatch（我的fork和trishume的原始版本）不支持自定义军刀的资产注入。您遇到的问题可能是由于版本问题 - BeatOn可能无法可靠地支持旧版本的Beat Saber。当我们可以复制问题并找到修复时，我会调查此问题并关闭它。

thank

**Comment by sc2ad** [comment]
As of now, BeatOn will not support versions less than 1.0.0. Please try to update to the latest version as soon as you can! Let me know if there is anything else I can help with.

**Comment by KarlDeux** [comment]
Closing this as seems to be solved.
