### ISSUE TITLE
Cover art error

### ISSUE THREAD

**Issue by KevinDenys** [emulamer/BeatOn#29]
When I added songs to Beat On, I received this error
`2019-07-10 21:42:07.002: MSG: AssetOpManager starting op of type AddNewSongToPlaylistOp
2019-07-10 21:42:07.046: ERR: Error loading cover art asset Object reference not set to an instance of an object   at QuestomAssets.BeatSaber.CustomLevelLoader.LoadSongCover (System.String songPath, QuestomAssets.BeatSaber.BeatmapLevelDataObject levelData) [0x00074] in <c7a1e0162c6c4bbda65e23f630f5b114>:0   ` for all my songs.

I can see the cover art in the beat on browser. But ingame there is no cover art.
![image](https://user-images.githubusercontent.com/17174443/61001024-ff7ac500-a35e-11e9-8638-885e8dff737a.png)

How can I fix this?

**Comment by KevinDenys** [comment]
![image](https://user-images.githubusercontent.com/17174443/61000985-ea059b00-a35e-11e9-955f-067963326277.png)
this is how it looks like ingame

**Comment by sekazi** [comment]
I have the same issue. Looking at the cover art on the BeatOnData\CustomSongs folder the cover art is correct inside of the folders but for whatever reason I get the generic image in Beat Saber.

**Comment by emulamer** [comment]
I think I've got this fixed in the next build that's going out along with a few other bugs.  Happening because I was setting the android centric image processing library on app startup instead of service startup, and SideQuest doesn't doesn't start the app.

**Comment by KarlDeux** [comment]
@sekazi @KevinDenys do you still have this issue?

**Comment by sekazi** [comment]
@KarlDeux I have not had the issue since I reset assets and the other things under tools. I am no longer importing from SideQuest so I do not think I will run into the issue again.

**Comment by emulamer** [comment]
I think this should also be fixed with the latest update since I'm loading the image library at the proper time.
