### ISSUE TITLE
After I patch beat saber, it tells me that there was an error and to reset assets in the tool menu. I can't find the *reset assets option in the* tool menu.

### ISSUE THREAD

**Issue by TheShibeGuy** [emulamer/BeatOn#33]

**Comment by shaneharris** [comment]
Hi there! sorry its possibly a bit confusing but there is a tools screen in both Beat On and in SideQuest. could that be it?

we should probably rename one of those

**Comment by hotdog374657** [comment]
Hey, my Beat On doesn't load to the menu so I can't access the tools screen.

**Comment by emulamer** [comment]
Also, the "Quick Fix" option will do the reset assets as part of it, and will preserve your playlists as well.

**Comment by KarlDeux** [comment]
Closing this as seems to be already covered.
