### ISSUE TITLE
Saber Colors wrong way around?

### ISSUE THREAD

**Issue by shaneharris** [emulamer/BeatOn#35]
![top](https://cdn.discordapp.com/attachments/592466014034460672/599883697281433600/Screenshot_763.png)

![bottom](https://cdn.discordapp.com/attachments/592466014034460672/599883701509292033/Screenshot_764.png)

**Comment by KarlDeux** [comment]
This issue should be fixed in the next release.

**Comment by KarlDeux** [comment]
This should be fixed now.
