### ISSUE TITLE
SyncSaber and existing songs

### ISSUE THREAD

**Issue by xAgent42x** [emulamer/BeatOn#49]
If a song is part of a syncsaber playlist but the song is not in the playlist, beat on will try to put that song back into the playlist after syncing syncsaber again.  The song will not transfer but will get a cover art place holder and song data.  The song will stay in the last place it was and it will stay there in game as well.  
![error1](https://user-images.githubusercontent.com/52130959/61572830-e7e3c080-aa71-11e9-92d8-ec9012b44d95.PNG)

**Comment by avluis** [comment]
This is unrelated to the issue at hand -- just wanted to know how you have SyncSaber set up (standalone version?)
