### ISSUE TITLE
BeatOn has stopping error.

### ISSUE THREAD

**Issue by xAgent42x** [emulamer/BeatOn#5]
BeatOn stops working every other time it is accessed in the headset.  The error is "BeatOn has stopped" at which point closing the app and reopening allows it to run again.

**Comment by emulamer** [comment]
Think maybe I have this fixed... android lifecycle doesn't play nice with the HttpListener, but stopping it and starting it HOPEFULLY will solve the issue.

**Comment by xAgent42x** [comment]
This is fixed in 0.0.4!  Great job emulamer!!!!
