### ISSUE TITLE
Easy way to update

### ISSUE THREAD

**Issue by ryanlauderbach** [emulamer/BeatOn#54]
A button that downloads and installs updates. That would be cool.
Also, for the time being, is there an easy way to update BeatOn without uninstalling and losing custom songs and mods?
I haven't updated yet so maybe it doesn't delete your songs but I don't know.

**Comment by xAgent42x** [comment]
It does not delete songs.  Simply update and go to tools and hit the quick fix button and all is good.

**Comment by ryanlauderbach** [comment]
Cool, thanks.

**Comment by KarlDeux** [comment]
I am closing this as seems to be fixed. Please, feel free to re-open the ticket if you require more assistance.
