### ISSUE TITLE
Bsaber.com voting for Quest users?

### ISSUE THREAD

**Issue by retorquere** [emulamer/BeatOn#55]
Will this open a path for bsaber.com voting for quest users? I'd love to give feedback on tracks I play.

**Comment by emulamer** [comment]
Probably eventually, but it'll very likely be in the form of a hook mod since it will mostly be useful within beatsaber.  With the progress that's being made there, it probably won't be too awfully long before we see some UI stuff being done via hook mods, then it's all downhill.
