### ISSUE TITLE
 Beat Saber Wants to Update After Patch is Applied

### ISSUE THREAD

**Issue by curvatura99** [emulamer/BeatOn#59]
Uninstall modded Beat Saber apk and install an untouched apk with update from the Oculus store. Apply the patch, assets, songs, etc. Oculus then wants to update the app everytime I launch the game. Most likely a version numbering issue somewhere in the modded apk.

**Comment by thomannator** [comment]
Same Issue here.  Have uninstalled and redone the whole process with BeatOn a few times.  Wasn't sure if the new update had gone through or not.

**Comment by emulamer** [comment]
Legit bug, due to a quick stopgap implementation of manifest modification.  Should have it fixed in the next release.

**Comment by wakster-mac-jee** [comment]
So is there any way to fix this before the update? If not do you have any estimation for the next release? Thanks.

**Comment by DASFREAQ** [comment]
Till it's fixed, just hit no to the update and you can still play.  :)

**Comment by emulamer** [comment]
Should be in the next day or two.  Since it's *mostly* working, I'm taking a little time to get a BS upgrade process in place so it's smoother in the future.

**Comment by curvatura99** [comment]
> Till it's fixed, just hit no to the update and you can still play. :)

This isn't a show stopper. It's just annoying when you have friends using the headset.

**Comment by xAgent42x** [comment]
This issue has been resolved with Beat On version 0.1.1.2
