### ISSUE TITLE
Random Ops stalling

### ISSUE THREAD

**Issue by xAgent42x** [emulamer/BeatOn#62]
Random ops will fail, stall or not complete and are not specific to one instance. Some fail when using syncsaber others are mods being installed, mods being turned on/off, quickfix or downloading playlists from bsaber.com.

**Comment by xAgent42x** [comment]
This has improved with version 0.1.1.2 but will leave open to check on next build.

**Comment by KarlDeux** [comment]
@xAgent42x is this already out?

**Comment by xAgent42x** [comment]
Closing issue as it has not occurred since posting.
