### ISSUE TITLE
Can't change sabers, Stuck with first installed saber

### ISSUE THREAD

**Issue by Hugues862** [emulamer/BeatOn#71]
I have a problem, i installed a saber using sidequest in the mods catergories and it worked fine but when i wanted to put a new one it gave me an error saying : ReplacedAssetOp
I am now stuck with these sabers ;/

**Comment by xAgent42x** [comment]
Ensure you are using g the latest Beat On (0.1.1.2) and updated Beat Saber (1.2.0).

**Comment by KarlDeux** [comment]
Hey, @Hugues862 I am closing this issue as there is no feedback from your side.
If you need anything else, please, feel free to open this issue again.
