### ISSUE TITLE
Crash/Freeze when browsing in the list of custom songs when playing.

### ISSUE THREAD

**Issue by Vasago** [emulamer/BeatOn#72]
Steps to reproduce the crash/freeze of beatsaber:

Get oculus quest
install latest SideQuest (0.6.3)
Install latest BeatOn application (0.1.1.2)
Download and load something like 100 custom songs (may be less) to your Oculus Device.
Listen to their preview a lot in the headset but dont enter/start playing any song, just listen to the previews.
When preview is still playing, start playing another preview of different song.
Repeat and listen to only previews for some time.
Application freezes whole Oculus Device after some time.

**Expected behavior**
It should not freeze the device.

**Screenshots**
Not needed. Just list of custom song in the device.

**Versions (please complete the following information):**
 - Beat Saber: [1.2.0]
 - Beat On Release: [0.1.1.2]
 - Sidequest  [0.6.3]

**Comment by emulamer** [comment]
There's not a whole lot I can do about it- it seems to be an issue within Beat Saber.  Fortunately, it looks like since 1.3 this has improved.
