### ISSUE TITLE
Increase max Syncsaber downloads

### ISSUE THREAD

**Issue by elmerohueso** [emulamer/BeatOn#74]
I want to be able to download more than 200 songs via Bookmarks in SyncSaber.

**Comment by cpetzel** [comment]
click the left arrow until you reach infinity

**Comment by elmerohueso** [comment]
Thanks! That's not extremely intuitive. Maybe add a not to that page
explaining that.

**Comment by KevinDenys** [comment]
When I click the left arrow it stops at 200?

**Comment by emulamer** [comment]
Other left arrow (where you'd expect 0 to be, it's infinity)
