### ISSUE TITLE
Upgrade to Beat Saber 1.3

### ISSUE THREAD

**Issue by curvatura99** [emulamer/BeatOn#75]
What's the ETA for Beat On working with version 1.3?

**Comment by Arakon** [comment]
Dude, seriously? There are major changes, it'll take time. Specifically emulamer's spare time. It'll be out when it's out.

**Comment by curvatura99** [comment]
> Dude, seriously? There are major changes, it'll take time. Specifically emulamer's spare time. It'll be out when it's out.

Thanks for the attitude. I would rather hear an answer from emulamer instead of a prick like you.
