### ISSUE TITLE
Im getting a error 

### ISSUE THREAD

**Issue by Ly-nxx** [emulamer/BeatOn#78]
When i try to load beaton it says Critical Error Something went wrong and beaton cant funsction and then says to reset assets in the tools menu but i cant find a reset assets button?

**Comment by ChildishGiant** [comment]
You're probably using an outdated/pirated version of Beat Saber

**Comment by Ly-nxx** [comment]
I dont Think i am I went On side quest and pressed the Beaton button to download doesn’t that work anymore?

**Comment by emulamer** [comment]
What version of beat saber?

**Comment by Ly-nxx** [comment]
The latest version

**Comment by Ly-nxx** [comment]
I’m assuming that’s why so now i want To know how to delete Beaton so i can Play neatsaver againe

**Comment by Ly-nxx** [comment]
Sorry for my trash spelling I’m on my phone

**Comment by emulamer** [comment]
Uninstall the beat saber app using sidequest then reinstall from the oculus store

**Comment by KarlDeux** [comment]
Hi @Ly-nxx, is your issue solved now?
