### ISSUE TITLE
Saber Color Selector

### ISSUE THREAD

**Issue by KpXDrgn** [emulamer/BeatOn#79]
**Describe the bug**
I recall previous versions of BeatOn had the option to choose Saber Colors for both the Left and Right Sabers which used to be located in the Mods section but that doesn't seem to be the case anymore...? Or am I recalling incorrectly?

**Expected behavior**
Restoring this option if it is indeed a bug or a response/update as to how to access it on the new release (0.1.3.3)

**Versions (please complete the following information):**
 - Beat Saber: 1.3.0.p1
 - Beat On Release: 0.1.3.3
 - Sidequest: 0.6.7

**Comment by xAgent42x** [comment]
Latest Beat Saber now allows for custom colors. Pretty sure the saber color selector for Beat On was removed for that reason. I believe this to be correct anyway.

**Comment by emulamer** [comment]
It was.  It's built in to the game now, so I didn't try to fix it for 1.3
