### ISSUE TITLE
BeatOn Saber Color Changer not Changing.

### ISSUE THREAD

**Issue by Hellomynameisjose** [emulamer/BeatOn#84]
When I go to change the colors for the saber I get an error message saying, "#1 Failed: ChangeColorOp"

how to show bug:
1. open SideQuest
2. open BeatOn (with Oculus Quest plugged in and connected.)
3. go to mods tab in BeatOn
4. attempt to change saber color

usually it would just change after 1-2 seconds, but now when I go to change the saber colors, I get an error message.

screenshot
<img width="1261" alt="Screen Shot 2019-09-14 at 7 16 40 PM" src="https://user-images.githubusercontent.com/55335600/64915456-713b0a80-d724-11e9-8c04-4c66c4641e08.png">

Versions
 - Beat Saber: 1.3
 - Beat On Release: 1.3.5
 - Sidequest  0.7.0

**Comment by xAgent42x** [comment]
Beat On 1.3.5 should not have saber colors available. That option has been removed because the newest version of Beat Saber has saber color change capability in game. You may need to do a fresh install of beat on.

**Comment by KarlDeux** [comment]
Closing this as saber color is now driven natively by BS and we do not offer support for previous versions of BS.
